export type JlptLevel = 'N5' | 'N4' | 'N3';

export interface KanjiEntry {
  kanji: string;
  readings: string[];
  meanings: string[];
  level: JlptLevel;
}

export const KANJI_DATA: KanjiEntry[] = [
  // ══════════════════════════════════════════════════════════════════════════
  // N5
  // ══════════════════════════════════════════════════════════════════════════
  { kanji: '一', readings: ['いち', 'いつ', 'ひと'], meanings: ['un', '1'], level: 'N5' },
  { kanji: '二', readings: ['に', 'ふた', 'ふ'], meanings: ['deux', '2'], level: 'N5' },
  { kanji: '三', readings: ['さん', 'み', 'みっ'], meanings: ['trois', '3'], level: 'N5' },
  { kanji: '四', readings: ['し', 'よん', 'よ', 'よっ'], meanings: ['quatre', '4'], level: 'N5' },
  { kanji: '五', readings: ['ご', 'いつ', 'いつつ'], meanings: ['cinq', '5'], level: 'N5' },
  { kanji: '六', readings: ['ろく', 'む', 'むっ', 'むい'], meanings: ['six', '6'], level: 'N5' },
  { kanji: '七', readings: ['しち', 'なな', 'なの'], meanings: ['sept', '7'], level: 'N5' },
  { kanji: '八', readings: ['はち', 'や', 'やっ'], meanings: ['huit', '8'], level: 'N5' },
  { kanji: '九', readings: ['く', 'きゅう', 'ここの'], meanings: ['neuf', '9'], level: 'N5' },
  { kanji: '十', readings: ['じゅう', 'じっ', 'とお', 'と'], meanings: ['dix', '10'], level: 'N5' },
  { kanji: '人', readings: ['じん', 'にん', 'ひと'], meanings: ['personne', 'humain'], level: 'N5' },
  { kanji: '今', readings: ['こん', 'きん', 'いま'], meanings: ['maintenant', 'présent', "aujourd'hui"], level: 'N5' },
  { kanji: '日', readings: ['にち', 'じつ', 'ひ', 'か'], meanings: ['jour', 'soleil', 'journée'], level: 'N5' },
  { kanji: '週', readings: ['しゅう'], meanings: ['semaine'], level: 'N5' },
  { kanji: '月', readings: ['げつ', 'がつ', 'つき'], meanings: ['lune', 'mois'], level: 'N5' },
  { kanji: '年', readings: ['ねん', 'とし'], meanings: ['année', 'an'], level: 'N5' },
  { kanji: '中', readings: ['ちゅう', 'なか'], meanings: ['milieu', 'intérieur', 'dedans'], level: 'N5' },
  { kanji: '山', readings: ['さん', 'やま'], meanings: ['montagne'], level: 'N5' },
  { kanji: '川', readings: ['せん', 'かわ'], meanings: ['rivière', 'fleuve'], level: 'N5' },
  { kanji: '左', readings: ['さ', 'ひだり'], meanings: ['gauche'], level: 'N5' },
  { kanji: '右', readings: ['う', 'みぎ'], meanings: ['droite'], level: 'N5' },
  { kanji: '大', readings: ['だい', 'たい', 'おお'], meanings: ['grand', 'gros'], level: 'N5' },
  { kanji: '木', readings: ['もく', 'ぼく', 'き', 'こ'], meanings: ['arbre', 'bois', 'jeudi'], level: 'N5' },
  { kanji: '本', readings: ['ほん', 'もと'], meanings: ['livre', 'origine', 'principal'], level: 'N5' },
  { kanji: '水', readings: ['すい', 'みず'], meanings: ['eau', 'mercredi'], level: 'N5' },
  { kanji: '火', readings: ['か', 'ひ'], meanings: ['feu', 'mardi'], level: 'N5' },
  { kanji: '父', readings: ['ふ', 'ちち'], meanings: ['père'], level: 'N5' },
  { kanji: '母', readings: ['ぼ', 'はは'], meanings: ['mère'], level: 'N5' },
  { kanji: '耳', readings: ['じ', 'みみ'], meanings: ['oreille'], level: 'N5' },
  { kanji: '口', readings: ['こう', 'くち'], meanings: ['bouche', 'entrée'], level: 'N5' },
  { kanji: '休', readings: ['きゅう', 'やす'], meanings: ['repos', 'se reposer', 'congé'], level: 'N5' },
  { kanji: '何', readings: ['なに', 'なん', 'か'], meanings: ['quoi', 'quel', 'combien'], level: 'N5' },
  { kanji: '入', readings: ['にゅう', 'い', 'はい', 'い'], meanings: ['entrer', 'mettre dedans'], level: 'N5' },
  { kanji: '上', readings: ['じょう', 'うえ', 'あ', 'のぼ'], meanings: ['dessus', 'haut', 'au-dessus'], level: 'N5' },
  { kanji: '前', readings: ['ぜん', 'まえ'], meanings: ['devant', 'avant', 'auparavant'], level: 'N5' },
  { kanji: '下', readings: ['か', 'げ', 'した', 'さ', 'くだ'], meanings: ['dessous', 'bas', 'en dessous'], level: 'N5' },
  { kanji: '千', readings: ['せん', 'ち'], meanings: ['mille', '1000'], level: 'N5' },
  { kanji: '午', readings: ['ご'], meanings: ['midi', 'cheval (signe zodiacal)'], level: 'N5' },
  { kanji: '友', readings: ['ゆう', 'とも'], meanings: ['ami', 'amitié'], level: 'N5' },
  { kanji: '古', readings: ['こ', 'ふる'], meanings: ['ancien', 'vieux'], level: 'N5' },
  { kanji: '名', readings: ['めい', 'みょう', 'な'], meanings: ['nom', 'renommé'], level: 'N5' },
  { kanji: '国', readings: ['こく', 'くに'], meanings: ['pays', 'nation'], level: 'N5' },
  { kanji: '外', readings: ['がい', 'げ', 'そと', 'ほか', 'はず'], meanings: ['extérieur', 'dehors', 'autre'], level: 'N5' },
  { kanji: '女', readings: ['じょ', 'にょ', 'おんな', 'め'], meanings: ['femme', 'féminin'], level: 'N5' },
  { kanji: '男', readings: ['だん', 'なん', 'おとこ'], meanings: ['homme', 'masculin'], level: 'N5' },
  { kanji: '子', readings: ['し', 'す', 'こ'], meanings: ['enfant', 'fils'], level: 'N5' },
  { kanji: '学', readings: ['がく', 'まな'], meanings: ['apprendre', 'étudier', 'école'], level: 'N5' },
  { kanji: '生', readings: ['せい', 'しょう', 'い', 'う', 'なま'], meanings: ['vie', 'naître', 'vivant', 'cru'], level: 'N5' },
  { kanji: '小', readings: ['しょう', 'ちい', 'こ', 'お'], meanings: ['petit'], level: 'N5' },
  { kanji: '書', readings: ['しょ', 'か'], meanings: ['écrire', 'livre', 'écriture'], level: 'N5' },
  { kanji: '毎', readings: ['まい'], meanings: ['chaque', 'tous les', 'chaque fois'], level: 'N5' },
  { kanji: '先', readings: ['せん', 'さき'], meanings: ['avant', 'devant', 'précédent', 'professeur'], level: 'N5' },
  { kanji: '会', readings: ['かい', 'え', 'あ'], meanings: ['rencontrer', 'réunion', 'association'], level: 'N5' },
  { kanji: '万', readings: ['まん', 'ばん'], meanings: ['dix mille', '10 000'], level: 'N5' },
  { kanji: '円', readings: ['えん', 'まる'], meanings: ['yen', 'cercle', 'rond'], level: 'N5' },
  { kanji: '出', readings: ['しゅつ', 'で', 'だ'], meanings: ['sortir', 'émerger', 'produire'], level: 'N5' },
  { kanji: '分', readings: ['ぶん', 'ふん', 'わ'], meanings: ['minute', 'comprendre', 'diviser', 'portion'], level: 'N5' },
  { kanji: '北', readings: ['ほく', 'きた'], meanings: ['nord'], level: 'N5' },
  { kanji: '半', readings: ['はん', 'なか'], meanings: ['moitié', 'demi'], level: 'N5' },
  { kanji: '南', readings: ['なん', 'みなみ'], meanings: ['sud'], level: 'N5' },
  { kanji: '土', readings: ['ど', 'つち'], meanings: ['terre', 'sol', 'samedi'], level: 'N5' },
  { kanji: '多', readings: ['た', 'おお'], meanings: ['beaucoup', 'nombreux'], level: 'N5' },
  { kanji: '天', readings: ['てん', 'あま', 'あめ'], meanings: ['ciel', 'paradis', 'temps'], level: 'N5' },
  { kanji: '安', readings: ['あん', 'やす'], meanings: ['bon marché', 'calme', 'sécurité'], level: 'N5' },
  { kanji: '少', readings: ['しょう', 'すこ', 'すく'], meanings: ['peu', 'faible', 'rare'], level: 'N5' },
  { kanji: '店', readings: ['てん', 'みせ'], meanings: ['magasin', 'boutique'], level: 'N5' },
  { kanji: '後', readings: ['ご', 'こう', 'あと', 'うし'], meanings: ['après', 'derrière', 'plus tard'], level: 'N5' },
  { kanji: '手', readings: ['しゅ', 'て'], meanings: ['main'], level: 'N5' },
  { kanji: '新', readings: ['しん', 'あたら', 'にい'], meanings: ['nouveau', 'neuf'], level: 'N5' },
  { kanji: '時', readings: ['じ', 'とき'], meanings: ['heure', 'temps', 'moment'], level: 'N5' },
  { kanji: '来', readings: ['らい', 'く', 'き', 'こ'], meanings: ['venir', 'arriver'], level: 'N5' },
  { kanji: '東', readings: ['とう', 'ひがし'], meanings: ['est'], level: 'N5' },
  { kanji: '校', readings: ['こう'], meanings: ['école'], level: 'N5' },
  { kanji: '気', readings: ['き', 'け'], meanings: ['énergie', 'esprit', 'atmosphère', 'sentiment'], level: 'N5' },
  { kanji: '白', readings: ['はく', 'びゃく', 'しろ', 'しら'], meanings: ['blanc'], level: 'N5' },
  { kanji: '百', readings: ['ひゃく', 'もも'], meanings: ['cent', '100'], level: 'N5' },
  { kanji: '目', readings: ['もく', 'め'], meanings: ['œil', 'yeux'], level: 'N5' },
  { kanji: '社', readings: ['しゃ', 'やしろ'], meanings: ['société', 'entreprise', 'sanctuaire'], level: 'N5' },
  { kanji: '空', readings: ['くう', 'そら', 'あ', 'から'], meanings: ['ciel', 'vide', 'air'], level: 'N5' },
  { kanji: '立', readings: ['りつ', 'りゅう', 'た'], meanings: ['se lever', 'debout', 'établir'], level: 'N5' },
  { kanji: '聞', readings: ['ぶん', 'もん', 'き'], meanings: ['entendre', 'écouter', 'demander'], level: 'N5' },
  { kanji: '花', readings: ['か', 'はな'], meanings: ['fleur'], level: 'N5' },
  { kanji: '行', readings: ['こう', 'ぎょう', 'い', 'ゆ', 'おこな'], meanings: ['aller', 'agir', 'rangée'], level: 'N5' },
  { kanji: '西', readings: ['せい', 'さい', 'にし'], meanings: ['ouest'], level: 'N5' },
  { kanji: '見', readings: ['けん', 'み'], meanings: ['voir', 'regarder', 'observer'], level: 'N5' },
  { kanji: '言', readings: ['げん', 'ごん', 'い', 'こと'], meanings: ['dire', 'parole'], level: 'N5' },
  { kanji: '話', readings: ['わ', 'はな', 'はなし'], meanings: ['parler', 'discours', 'histoire'], level: 'N5' },
  { kanji: '語', readings: ['ご', 'かた'], meanings: ['langue', 'mot', 'parler'], level: 'N5' },
  { kanji: '読', readings: ['どく', 'とく', 'よ'], meanings: ['lire'], level: 'N5' },
  { kanji: '買', readings: ['ばい', 'か'], meanings: ['acheter'], level: 'N5' },
  { kanji: '足', readings: ['そく', 'あし'], meanings: ['pied', 'jambe', 'suffisant'], level: 'N5' },
  { kanji: '車', readings: ['しゃ', 'くるま'], meanings: ['voiture', 'véhicule'], level: 'N5' },
  { kanji: '道', readings: ['どう', 'みち'], meanings: ['route', 'chemin', 'voie'], level: 'N5' },
  { kanji: '金', readings: ['きん', 'こん', 'かね', 'かな'], meanings: ['or', 'argent', 'vendredi'], level: 'N5' },
  { kanji: '長', readings: ['ちょう', 'なが'], meanings: ['long', 'chef', 'directeur'], level: 'N5' },
  { kanji: '間', readings: ['かん', 'けん', 'あいだ', 'ま'], meanings: ['intervalle', 'entre', 'espace de temps'], level: 'N5' },
  { kanji: '雨', readings: ['う', 'あめ', 'あま'], meanings: ['pluie'], level: 'N5' },
  { kanji: '電', readings: ['でん'], meanings: ['électricité', 'électrique'], level: 'N5' },
  { kanji: '食', readings: ['しょく', 'た', 'く'], meanings: ['manger', 'nourriture'], level: 'N5' },
  { kanji: '飲', readings: ['いん', 'の'], meanings: ['boire'], level: 'N5' },
  { kanji: '駅', readings: ['えき'], meanings: ['gare', 'station'], level: 'N5' },
  { kanji: '高', readings: ['こう', 'たか'], meanings: ['haut', 'élevé', 'cher'], level: 'N5' },
  { kanji: '魚', readings: ['ぎょ', 'さかな', 'うお'], meanings: ['poisson'], level: 'N5' },

  // ══════════════════════════════════════════════════════════════════════════
  // N4
  // ══════════════════════════════════════════════════════════════════════════
  { kanji: '力', readings: ['りょく', 'りき', 'ちから'], meanings: ['force', 'puissance', 'énergie'], level: 'N4' },
  { kanji: '夕', readings: ['せき', 'ゆう'], meanings: ['soir', 'crépuscule'], level: 'N4' },
  { kanji: '工', readings: ['こう', 'く'], meanings: ['artisan', 'travail', 'construction', 'ingénierie'], level: 'N4' },
  { kanji: '元', readings: ['げん', 'がん', 'もと'], meanings: ['origine', 'source', 'racine', 'ancien'], level: 'N4' },
  { kanji: '止', readings: ['し', 'と', 'や'], meanings: ['arrêter', "s'arrêter", 'stopper'], level: 'N4' },
  { kanji: '引', readings: ['いん', 'ひ'], meanings: ['tirer', 'attirer', 'conduire'], level: 'N4' },
  { kanji: '牛', readings: ['ぎゅう', 'うし'], meanings: ['vache', 'bœuf', 'taureau'], level: 'N4' },
  { kanji: '区', readings: ['く'], meanings: ['quartier', 'district', 'arrondissement'], level: 'N4' },
  { kanji: '犬', readings: ['けん', 'いぬ'], meanings: ['chien'], level: 'N4' },
  { kanji: '不', readings: ['ふ', 'ぶ'], meanings: ['non-', 'in-', 'sans', 'mauvais'], level: 'N4' },
  { kanji: '文', readings: ['ぶん', 'もん', 'ふみ'], meanings: ['texte', 'écriture', 'culture', 'lettre'], level: 'N4' },
  { kanji: '方', readings: ['ほう', 'かた'], meanings: ['direction', 'méthode', 'personne', 'côté'], level: 'N4' },
  { kanji: '心', readings: ['しん', 'こころ'], meanings: ['cœur', 'esprit', 'âme', 'centre'], level: 'N4' },
  { kanji: '切', readings: ['せつ', 'さい', 'き'], meanings: ['couper', 'urgent', 'important'], level: 'N4' },
  { kanji: '太', readings: ['たい', 'た', 'ふと'], meanings: ['gros', 'épais', 'large', 'audacieux'], level: 'N4' },
  { kanji: '代', readings: ['だい', 'たい', 'か', 'しろ'], meanings: ['génération', 'époque', 'remplacer', 'frais'], level: 'N4' },
  { kanji: '台', readings: ['だい', 'たい'], meanings: ['support', 'plate-forme', 'compteur (machines)'], level: 'N4' },
  { kanji: '世', readings: ['せ', 'せい', 'よ'], meanings: ['monde', 'génération', 'époque', 'société'], level: 'N4' },
  { kanji: '正', readings: ['せい', 'しょう', 'ただ', 'まさ'], meanings: ['correct', 'juste', 'exact', 'droit'], level: 'N4' },
  { kanji: '田', readings: ['でん', 'た'], meanings: ['rizière', 'champ'], level: 'N4' },
  { kanji: '冬', readings: ['とう', 'ふゆ'], meanings: ['hiver'], level: 'N4' },
  { kanji: '民', readings: ['みん', 'たみ'], meanings: ['peuple', 'nation', 'civil'], level: 'N4' },
  { kanji: '用', readings: ['よう', 'もち'], meanings: ['usage', 'utiliser', 'affaire', 'besoin'], level: 'N4' },
  { kanji: '兄', readings: ['けい', 'きょう', 'あに'], meanings: ['frère aîné'], level: 'N4' },
  { kanji: '以', readings: ['い'], meanings: ['plus que', 'depuis', 'au-delà de'], level: 'N4' },
  { kanji: '去', readings: ['きょ', 'こ', 'さ'], meanings: ['partir', 'passer', "l'année dernière", 'passé'], level: 'N4' },
  { kanji: '仕', readings: ['し', 'つか'], meanings: ['servir', 'service', 'travail'], level: 'N4' },
  { kanji: '市', readings: ['し', 'いち'], meanings: ['ville', 'marché', 'municipal'], level: 'N4' },
  { kanji: '広', readings: ['こう', 'ひろ'], meanings: ['large', 'spacieux', 'étendre'], level: 'N4' },
  { kanji: '主', readings: ['しゅ', 'す', 'ぬし', 'おも'], meanings: ['principal', 'maître', 'propriétaire', 'Seigneur'], level: 'N4' },
  { kanji: '写', readings: ['しゃ', 'うつ'], meanings: ['copier', 'photographier', 'transcrire'], level: 'N4' },
  { kanji: '字', readings: ['じ', 'あざ'], meanings: ['caractère', 'lettre', 'écriture'], level: 'N4' },
  { kanji: '自', readings: ['じ', 'し', 'みずか'], meanings: ['soi-même', 'auto-', 'propre'], level: 'N4' },
  { kanji: '考', readings: ['こう', 'かんが'], meanings: ['penser', 'réfléchir', 'examiner'], level: 'N4' },
  { kanji: '合', readings: ['ごう', 'が', 'あ', 'あわ'], meanings: ['correspondre', 'combiner', 'réunir', 'accord'], level: 'N4' },
  { kanji: '光', readings: ['こう', 'ひかり', 'ひか'], meanings: ['lumière', 'lueur', 'briller', 'gloire'], level: 'N4' },
  { kanji: '好', readings: ['こう', 'す', 'よ'], meanings: ['aimer', 'bon', 'favori'], level: 'N4' },
  { kanji: '死', readings: ['し'], meanings: ['mourir', 'mort'], level: 'N4' },
  { kanji: '回', readings: ['かい', 'まわ'], meanings: ['tourner', 'fois', 'tour'], level: 'N4' },
  { kanji: '有', readings: ['ゆう', 'う', 'あ'], meanings: ['avoir', 'exister', 'posséder'], level: 'N4' },
  { kanji: '同', readings: ['どう', 'おな'], meanings: ['même', 'identique', 'ensemble'], level: 'N4' },
  { kanji: '肉', readings: ['にく'], meanings: ['viande', 'chair'], level: 'N4' },
  { kanji: '色', readings: ['しょく', 'しき', 'いろ'], meanings: ['couleur', 'teinte', 'désir'], level: 'N4' },
  { kanji: '早', readings: ['そう', 'さっ', 'はや'], meanings: ['tôt', 'rapide', 'matinal'], level: 'N4' },
  { kanji: '地', readings: ['ち', 'じ'], meanings: ['terre', 'sol', 'lieu', 'terrain'], level: 'N4' },
  { kanji: '池', readings: ['ち', 'いけ'], meanings: ['étang', 'mare', 'bassin'], level: 'N4' },
  { kanji: '村', readings: ['そん', 'むら'], meanings: ['village'], level: 'N4' },
  { kanji: '体', readings: ['たい', 'てい', 'からだ'], meanings: ['corps', 'physique', 'forme'], level: 'N4' },
  { kanji: '町', readings: ['ちょう', 'まち'], meanings: ['ville', 'quartier', 'rue'], level: 'N4' },
  { kanji: '低', readings: ['てい', 'ひく'], meanings: ['bas', 'peu élevé', 'faible'], level: 'N4' },
  { kanji: '弟', readings: ['てい', 'だい', 'おとうと'], meanings: ['frère cadet'], level: 'N4' },
  { kanji: '走', readings: ['そう', 'はし'], meanings: ['courir'], level: 'N4' },
  { kanji: '赤', readings: ['せき', 'しゃく', 'あか'], meanings: ['rouge'], level: 'N4' },
  { kanji: '図', readings: ['ず', 'と', 'はか'], meanings: ['plan', 'figure', 'carte', 'dessin'], level: 'N4' },
  { kanji: '究', readings: ['きゅう', 'く'], meanings: ['rechercher', 'explorer à fond', 'étudier'], level: 'N4' },
  { kanji: '声', readings: ['せい', 'しょう', 'こえ'], meanings: ['voix', 'son'], level: 'N4' },
  { kanji: '売', readings: ['ばい', 'う'], meanings: ['vendre'], level: 'N4' },
  { kanji: '別', readings: ['べつ', 'わか'], meanings: ['séparé', 'différent', 'autre', 'spécial'], level: 'N4' },
  { kanji: '医', readings: ['い'], meanings: ['médecine', 'médecin', 'docteur'], level: 'N4' },
  { kanji: '近', readings: ['きん', 'ちか'], meanings: ['proche', 'récent', 'voisin'], level: 'N4' },
  { kanji: '私', readings: ['し', 'わたし', 'わたくし'], meanings: ['je', 'moi', 'privé'], level: 'N4' },
  { kanji: '作', readings: ['さく', 'さ', 'つく'], meanings: ['faire', 'créer', 'fabriquer', 'composer'], level: 'N4' },
  { kanji: '住', readings: ['じゅう', 'す', 'すま'], meanings: ['habiter', 'résider', 'logement'], level: 'N4' },
  { kanji: '者', readings: ['しゃ', 'もの'], meanings: ['personne', 'celui qui', 'individu'], level: 'N4' },
  { kanji: '事', readings: ['じ', 'ず', 'こと'], meanings: ['affaire', 'chose', 'travail', 'événement'], level: 'N4' },
  { kanji: '使', readings: ['し', 'つか'], meanings: ['utiliser', 'employer', 'messager'], level: 'N4' },
  { kanji: '始', readings: ['し', 'はじ'], meanings: ['commencer', 'début', 'démarrer'], level: 'N4' },
  { kanji: '姉', readings: ['し', 'あね'], meanings: ['sœur aînée'], level: 'N4' },
  { kanji: '英', readings: ['えい'], meanings: ['Angleterre', 'héroïque', 'excellent', 'fleur'], level: 'N4' },
  { kanji: '京', readings: ['きょう', 'けい', 'みやこ'], meanings: ['capitale', 'Tokyo', 'Kyoto'], level: 'N4' },
  { kanji: '画', readings: ['が', 'かく', 'え'], meanings: ['image', 'dessin', 'peinture', 'film'], level: 'N4' },
  { kanji: '妹', readings: ['まい', 'いもうと'], meanings: ['sœur cadette'], level: 'N4' },
  { kanji: '味', readings: ['み', 'あじ'], meanings: ['goût', 'saveur', 'intérêt'], level: 'N4' },
  { kanji: '服', readings: ['ふく'], meanings: ['vêtement', 'habit', 'obéir'], level: 'N4' },
  { kanji: '物', readings: ['もつ', 'ぶつ', 'もの'], meanings: ['chose', 'objet', 'matière'], level: 'N4' },
  { kanji: '歩', readings: ['ほ', 'ぶ', 'ある', 'あゆ'], meanings: ['marcher', 'pas', 'aller à pied'], level: 'N4' },
  { kanji: '門', readings: ['もん', 'かど'], meanings: ['porte', 'portail', 'famille'], level: 'N4' },
  { kanji: '夜', readings: ['や', 'よ', 'よる'], meanings: ['nuit', 'soir'], level: 'N4' },
  { kanji: '明', readings: ['めい', 'みょう', 'あか', 'あき'], meanings: ['clair', 'brillant', 'demain', 'lumineux'], level: 'N4' },
  { kanji: '林', readings: ['りん', 'はやし'], meanings: ['forêt', 'bois', 'bosquet'], level: 'N4' },
  { kanji: '青', readings: ['せい', 'しょう', 'あお'], meanings: ['bleu', 'vert', 'jeune'], level: 'N4' },
  { kanji: '所', readings: ['しょ', 'ところ'], meanings: ['endroit', 'lieu', 'place', 'bureau'], level: 'N4' },
  { kanji: '注', readings: ['ちゅう', 'そそ', 'つ'], meanings: ['verser', 'noter', 'attention', 'commander'], level: 'N4' },
  { kanji: '知', readings: ['ち', 'し'], meanings: ['savoir', 'connaissance', 'connaître'], level: 'N4' },
  { kanji: '昼', readings: ['ちゅう', 'ひる'], meanings: ['midi', 'journée', 'après-midi'], level: 'N4' },
  { kanji: '茶', readings: ['ちゃ', 'さ'], meanings: ['thé', 'brun', 'marron'], level: 'N4' },
  { kanji: '待', readings: ['たい', 'ま'], meanings: ['attendre', 'inviter', 'traiter'], level: 'N4' },
  { kanji: '洗', readings: ['せん', 'あら'], meanings: ['laver', 'rincer', 'nettoyer'], level: 'N4' },
  { kanji: '送', readings: ['そう', 'おく'], meanings: ['envoyer', 'accompagner', 'passer (temps)'], level: 'N4' },
  { kanji: '品', readings: ['ひん', 'ぴん', 'しな'], meanings: ['article', 'qualité', 'dignité', 'produit'], level: 'N4' },
  { kanji: '洋', readings: ['よう'], meanings: ['occidental', 'océan', 'Occident'], level: 'N4' },
  { kanji: '便', readings: ['べん', 'びん', 'たよ'], meanings: ['pratique', 'courrier', 'commodité'], level: 'N4' },
  { kanji: '風', readings: ['ふう', 'ふ', 'かぜ', 'かざ'], meanings: ['vent', 'style', 'mode', 'apparence'], level: 'N4' },
  { kanji: '発', readings: ['はつ', 'ほつ', 'た'], meanings: ['partir', 'émettre', 'publier', 'développer'], level: 'N4' },
  { kanji: '度', readings: ['ど', 'たび', 'たく'], meanings: ['degré', 'fois', 'mesure', 'fois'], level: 'N4' },
  { kanji: '映', readings: ['えい'], meanings: ['projection', 'film', 'reflet', 'briller'], level: 'N4' },
  { kanji: '海', readings: ['かい', 'うみ'], meanings: ['mer', 'océan'], level: 'N4' },
  { kanji: '界', readings: ['かい'], meanings: ['monde', 'limite', 'domaine', 'milieu'], level: 'N4' },
  { kanji: '屋', readings: ['おく', 'や'], meanings: ['magasin', 'toit', 'pièce', 'vendeur de'], level: 'N4' },
  { kanji: '音', readings: ['おん', 'いん', 'おと', 'ね'], meanings: ['son', 'bruit', 'musique', 'nouvelle'], level: 'N4' },
  { kanji: '急', readings: ['きゅう', 'いそ'], meanings: ['urgent', 'rapide', 'soudain'], level: 'N4' },
  { kanji: '計', readings: ['けい', 'はか'], meanings: ['calculer', 'plan', 'mesure', 'compteur'], level: 'N4' },
  { kanji: '建', readings: ['けん', 'こん', 'た'], meanings: ['construire', 'bâtir', 'établir'], level: 'N4' },
  { kanji: '研', readings: ['けん', 'と'], meanings: ['polir', 'étudier', 'rechercher'], level: 'N4' },
  { kanji: '県', readings: ['けん'], meanings: ['préfecture'], level: 'N4' },
  { kanji: '思', readings: ['し', 'おも'], meanings: ['penser', 'croire', 'ressentir'], level: 'N4' },
  { kanji: '乗', readings: ['じょう', 'の'], meanings: ['monter', 'embarquer', 'multiplier'], level: 'N4' },
  { kanji: '重', readings: ['じゅう', 'ちょう', 'おも', 'かさ'], meanings: ['lourd', 'important', 'couches', 'grave'], level: 'N4' },
  { kanji: '春', readings: ['しゅん', 'はる'], meanings: ['printemps'], level: 'N4' },
  { kanji: '室', readings: ['しつ', 'むろ'], meanings: ['pièce', 'chambre', 'salle', 'bureau'], level: 'N4' },
  { kanji: '持', readings: ['じ', 'も'], meanings: ['tenir', 'posséder', 'porter', 'durer'], level: 'N4' },
  { kanji: '首', readings: ['しゅ', 'くび'], meanings: ['cou', 'tête', 'chef', 'poème'], level: 'N4' },
  { kanji: '秋', readings: ['しゅう', 'あき'], meanings: ['automne'], level: 'N4' },
  { kanji: '借', readings: ['しゃく', 'か'], meanings: ['emprunter', 'louer', 'se servir de'], level: 'N4' },
  { kanji: '弱', readings: ['じゃく', 'よわ'], meanings: ['faible', 'fragile', 'peu'], level: 'N4' },
  { kanji: '紙', readings: ['し', 'かみ'], meanings: ['papier', 'lettre', 'journal'], level: 'N4' },
  { kanji: '帰', readings: ['き', 'かえ'], meanings: ['rentrer', 'retourner', 'revenir'], level: 'N4' },
  { kanji: '起', readings: ['き', 'お'], meanings: ['se lever', 'se produire', 'éveiller'], level: 'N4' },
  { kanji: '夏', readings: ['か', 'なつ'], meanings: ['été'], level: 'N4' },
  { kanji: '家', readings: ['か', 'け', 'いえ', 'や'], meanings: ['maison', 'famille', 'foyer', 'expert'], level: 'N4' },
  { kanji: '院', readings: ['いん'], meanings: ['institution', 'hôpital', 'temple', 'cour'], level: 'N4' },
  { kanji: '員', readings: ['いん'], meanings: ['membre', 'employé', 'fonctionnaire'], level: 'N4' },
  { kanji: '病', readings: ['びょう', 'へい', 'や'], meanings: ['maladie', 'malade', 'infirmité'], level: 'N4' },
  { kanji: '勉', readings: ['べん'], meanings: ["s'efforcer", 'étudier', 'travailler dur'], level: 'N4' },
  { kanji: '特', readings: ['とく'], meanings: ['spécial', 'particulier', 'unique'], level: 'N4' },
  { kanji: '旅', readings: ['りょ', 'たび'], meanings: ['voyage', 'trip'], level: 'N4' },
  { kanji: '料', readings: ['りょう'], meanings: ['frais', 'ingrédient', 'matériau', 'tarif'], level: 'N4' },
  { kanji: '真', readings: ['しん', 'ま'], meanings: ['vrai', 'réel', 'sincère', 'photo'], level: 'N4' },
  { kanji: '通', readings: ['つう', 'かよ', 'とお'], meanings: ['passer', 'traverser', 'communiquer', 'rue'], level: 'N4' },
  { kanji: '鳥', readings: ['ちょう', 'とり'], meanings: ['oiseau'], level: 'N4' },
  { kanji: '転', readings: ['てん', 'ころ'], meanings: ['tourner', 'rouler', 'changer', 'tomber'], level: 'N4' },
  { kanji: '族', readings: ['ぞく'], meanings: ['famille', 'tribu', 'clan', 'groupe'], level: 'N4' },
  { kanji: '進', readings: ['しん', 'すす'], meanings: ['avancer', 'progresser', 'pousser en avant'], level: 'N4' },
  { kanji: '理', readings: ['り'], meanings: ['raison', 'logique', 'principe', 'ordonner'], level: 'N4' },
  { kanji: '野', readings: ['や', 'の'], meanings: ['champ', 'nature', 'sauvage', 'champ (sport)'], level: 'N4' },
  { kanji: '問', readings: ['もん', 'と', 'とい'], meanings: ['question', 'problème', 'demander'], level: 'N4' },
  { kanji: '都', readings: ['と', 'つ', 'みやこ'], meanings: ['capitale', 'métropole', 'Tokyo', 'tous'], level: 'N4' },
  { kanji: '堂', readings: ['どう'], meanings: ['salle', 'édifice', 'temple', 'imposant'], level: 'N4' },
  { kanji: '動', readings: ['どう', 'うご'], meanings: ['bouger', 'mouvement', 'émouvoir', 'agir'], level: 'N4' },
  { kanji: '悪', readings: ['あく', 'お', 'わる'], meanings: ['mauvais', 'mal', 'méchant', 'mauvaise qualité'], level: 'N4' },
  { kanji: '強', readings: ['きょう', 'つよ', 'し'], meanings: ['fort', 'puissant', 'vigoureux'], level: 'N4' },
  { kanji: '教', readings: ['きょう', 'おし', 'おそ'], meanings: ['enseigner', 'éducation', 'religion', 'doctrine'], level: 'N4' },
  { kanji: '産', readings: ['さん', 'う'], meanings: ['produire', 'naissance', 'produit', 'industrie'], level: 'N4' },
  { kanji: '黒', readings: ['こく', 'くろ'], meanings: ['noir'], level: 'N4' },
  { kanji: '菜', readings: ['さい', 'な'], meanings: ['légume', 'verdure', 'herbe'], level: 'N4' },
  { kanji: '終', readings: ['しゅう', 'お'], meanings: ['finir', 'terminer', 'fin'], level: 'N4' },
  { kanji: '習', readings: ['しゅう', 'なら'], meanings: ['apprendre', 'pratiquer', 'habitude'], level: 'N4' },
  { kanji: '集', readings: ['しゅう', 'あつ'], meanings: ['rassembler', 'réunir', 'collection'], level: 'N4' },
  { kanji: '場', readings: ['じょう', 'ば'], meanings: ['lieu', 'endroit', 'scène', 'terrain'], level: 'N4' },
  { kanji: '寒', readings: ['かん', 'さむ'], meanings: ['froid', 'hivernal'], level: 'N4' },
  { kanji: '軽', readings: ['けい', 'かる', 'かろ'], meanings: ['léger', 'facile', 'frivole', 'peu sérieux'], level: 'N4' },
  { kanji: '運', readings: ['うん', 'はこ'], meanings: ['chance', 'destin', 'transporter', 'sort'], level: 'N4' },
  { kanji: '開', readings: ['かい', 'あ', 'ひら'], meanings: ['ouvrir', 'commencer', 'développer'], level: 'N4' },
  { kanji: '飯', readings: ['はん', 'めし'], meanings: ['riz cuit', 'repas'], level: 'N4' },
  { kanji: '答', readings: ['とう', 'こた'], meanings: ['réponse', 'répondre'], level: 'N4' },
  { kanji: '森', readings: ['しん', 'もり'], meanings: ['forêt', 'bois dense'], level: 'N4' },
  { kanji: '暑', readings: ['しょ', 'あつ'], meanings: ['chaud (temps)', 'chaleur estivale'], level: 'N4' },
  { kanji: '朝', readings: ['ちょう', 'あさ'], meanings: ['matin', 'cour impériale'], level: 'N4' },
  { kanji: '貸', readings: ['たい', 'か'], meanings: ['prêter', 'louer', 'mettre à disposition'], level: 'N4' },
  { kanji: '着', readings: ['ちゃく', 'き', 'つ'], meanings: ['arriver', 'porter (vêtement)', 'adhérer'], level: 'N4' },
  { kanji: '短', readings: ['たん', 'みじか'], meanings: ['court', 'bref', 'défaut'], level: 'N4' },
  { kanji: '働', readings: ['どう', 'はたら'], meanings: ['travailler', 'fonctionner', 'opérer'], level: 'N4' },
  { kanji: '楽', readings: ['がく', 'らく', 'たの'], meanings: ['musique', 'facile', 'agréable', 'amusant'], level: 'N4' },
  { kanji: '暗', readings: ['あん', 'くら'], meanings: ['sombre', 'obscur', 'ténèbres'], level: 'N4' },
  { kanji: '意', readings: ['い'], meanings: ['intention', 'sens', 'esprit', 'opinion'], level: 'N4' },
  { kanji: '遠', readings: ['えん', 'おん', 'とお'], meanings: ['loin', 'distant'], level: 'N4' },
  { kanji: '漢', readings: ['かん', 'おとこ'], meanings: ['caractère chinois', 'Chinois', 'homme'], level: 'N4' },
  { kanji: '業', readings: ['ぎょう', 'ごう', 'わざ'], meanings: ['travail', 'industrie', 'karma', 'profession'], level: 'N4' },
  { kanji: '試', readings: ['し', 'こころ', 'ため'], meanings: ['essayer', 'tester', 'examen'], level: 'N4' },
  { kanji: '銀', readings: ['ぎん'], meanings: ['argent (métal)', 'argent (couleur)', 'banque'], level: 'N4' },
  { kanji: '歌', readings: ['か', 'うた'], meanings: ['chanter', 'chanson', 'waka (poème)'], level: 'N4' },
  { kanji: '説', readings: ['せつ', 'ぜい', 'と'], meanings: ['explication', 'théorie', 'convaincre'], level: 'N4' },
  { kanji: '質', readings: ['しつ', 'しち', 'たち'], meanings: ['qualité', 'nature', 'gage', 'matière'], level: 'N4' },
  { kanji: '館', readings: ['かん', 'やかた'], meanings: ['bâtiment', 'hall', 'auberge', 'musée'], level: 'N4' },
  { kanji: '親', readings: ['しん', 'おや', 'した'], meanings: ['parent', 'intime', 'proche', 'affection'], level: 'N4' },
  { kanji: '頭', readings: ['とう', 'ず', 'あたま', 'かしら'], meanings: ['tête', 'chef', 'début', 'intelligence'], level: 'N4' },
  { kanji: '薬', readings: ['やく', 'くすり'], meanings: ['médicament', 'remède', 'drogue'], level: 'N4' },
  { kanji: '曜', readings: ['よう'], meanings: ['jour de la semaine'], level: 'N4' },
  { kanji: '題', readings: ['だい'], meanings: ['titre', 'sujet', 'thème', 'problème'], level: 'N4' },
  { kanji: '顔', readings: ['がん', 'かお'], meanings: ['visage', 'figure', 'expression'], level: 'N4' },
  { kanji: '験', readings: ['けん', 'げん'], meanings: ['expérience', 'examen', 'vérification', 'résultat'], level: 'N4' },

  // ══════════════════════════════════════════════════════════════════════════
  // N3
  // ══════════════════════════════════════════════════════════════════════════
  { kanji: '全', readings: ['ぜん', 'すべ', 'まった'], meanings: ['tout', 'entier', 'complet'], level: 'N3' },
  { kanji: '部', readings: ['ぶ', 'へや'], meanings: ['partie', 'section', 'pièce', 'club'], level: 'N3' },
  { kanji: '化', readings: ['か', 'け', 'ば'], meanings: ['changer', 'transformer', 'culture'], level: 'N3' },
  { kanji: '的', readings: ['てき'], meanings: ['cible', 'but', '-ique (suffixe adjectival)'], level: 'N3' },
  { kanji: '内', readings: ['ない', 'だい', 'うち'], meanings: ['intérieur', 'dedans', 'interne'], level: 'N3' },
  { kanji: '政', readings: ['せい', 'しょう'], meanings: ['politique', 'gouvernement', 'administration'], level: 'N3' },
  { kanji: '治', readings: ['じ', 'ち', 'おさ', 'なお'], meanings: ['gouverner', 'guérir', 'calmer', 'administrer'], level: 'N3' },
  { kanji: '経', readings: ['けい', 'きょう', 'へ'], meanings: ['traverser', 'gérer', 'économie', 'passer'], level: 'N3' },
  { kanji: '済', readings: ['さい', 'す', 'すく'], meanings: ['terminer', 'finir', 'économie', 'sauver'], level: 'N3' },
  { kanji: '法', readings: ['ほう', 'は', 'のり'], meanings: ['loi', 'méthode', 'règle', 'Dharma'], level: 'N3' },
  { kanji: '科', readings: ['か'], meanings: ['science', 'département', 'matière (scolaire)', 'catégorie'], level: 'N3' },
  { kanji: '技', readings: ['ぎ', 'わざ'], meanings: ['technique', 'compétence', 'art', 'habilité'], level: 'N3' },
  { kanji: '術', readings: ['じゅつ'], meanings: ['technique', 'art', 'méthode', 'magie'], level: 'N3' },
  { kanji: '発', readings: ['はつ', 'ほつ', 'た'], meanings: ['émettre', 'partir', 'publier', 'développer'], level: 'N3' },
  { kanji: '表', readings: ['ひょう', 'おもて', 'あらわ'], meanings: ['surface', 'exprimer', 'tableau', 'représenter'], level: 'N3' },
  { kanji: '現', readings: ['げん', 'あらわ'], meanings: ['présent', 'apparaître', 'actuel', 'réel'], level: 'N3' },
  { kanji: '実', readings: ['じつ', 'み', 'みの'], meanings: ['réalité', 'fruit', 'vérité', 'sincérité'], level: 'N3' },
  { kanji: '感', readings: ['かん'], meanings: ['sensation', 'sentir', 'émotion', 'impressionner'], level: 'N3' },
  { kanji: '情', readings: ['じょう', 'せい', 'なさ'], meanings: ['sentiment', 'émotion', 'affection', 'information'], level: 'N3' },
  { kanji: '識', readings: ['しき'], meanings: ['conscience', 'connaissance', 'discerner'], level: 'N3' },
  { kanji: '記', readings: ['き', 'しる'], meanings: ['noter', 'enregistrer', 'mémoriser', 'chroniquer'], level: 'N3' },
  { kanji: '想', readings: ['そう', 'そ'], meanings: ['penser', 'imaginer', 'concept', 'idée'], level: 'N3' },
  { kanji: '決', readings: ['けつ', 'き', 'さ'], meanings: ['décider', 'résoudre', 'déterminer', 'juger'], level: 'N3' },
  { kanji: '定', readings: ['てい', 'じょう', 'さだ'], meanings: ['fixer', 'décider', 'stable', 'règle'], level: 'N3' },
  { kanji: '議', readings: ['ぎ'], meanings: ['discussion', 'délibération', 'réunion', 'débattre'], level: 'N3' },
  { kanji: '論', readings: ['ろん'], meanings: ['débat', 'théorie', 'discuter', 'argument'], level: 'N3' },
  { kanji: '結', readings: ['けつ', 'むす', 'ゆ'], meanings: ['lier', 'résultat', 'conclure', 'mariage'], level: 'N3' },
  { kanji: '果', readings: ['か', 'は', 'はて', 'はた'], meanings: ['résultat', 'fruit', 'accomplir', 'finalement'], level: 'N3' },
  { kanji: '利', readings: ['り', 'き'], meanings: ['profit', 'intérêt', 'utile', 'avantage'], level: 'N3' },
  { kanji: '勝', readings: ['しょう', 'か'], meanings: ['gagner', 'victoire', 'supérieur'], level: 'N3' },
  { kanji: '戦', readings: ['せん', 'たたか', 'いくさ'], meanings: ['guerre', 'combat', 'bataille', 'compétition'], level: 'N3' },
  { kanji: '的', readings: ['てき'], meanings: ['cible', 'but', 'objectif', '-ique'], level: 'N3' },
  { kanji: '国', readings: ['こく', 'くに'], meanings: ['pays', 'nation', 'état', 'patrie'], level: 'N3' },
  { kanji: '際', readings: ['さい', 'きわ'], meanings: ['occasion', 'bord', 'relation internationale', 'lors de'], level: 'N3' },
  { kanji: '関', readings: ['かん', 'せき', 'かか'], meanings: ['relation', 'barrière', 'concerner', 'ligaturer'], level: 'N3' },
  { kanji: '様', readings: ['よう', 'さま'], meanings: ['apparence', 'forme', 'manière', 'Monsieur/Madame'], level: 'N3' },
  { kanji: '次', readings: ['じ', 'し', 'つぎ', 'つぐ'], meanings: ['suivant', 'prochain', 'ordre', 'après'], level: 'N3' },
  { kanji: '使', readings: ['し', 'つか'], meanings: ['utiliser', 'employer', 'ambassadeur'], level: 'N3' },
  { kanji: '受', readings: ['じゅ', 'う'], meanings: ['recevoir', 'accepter', 'subir'], level: 'N3' },
  { kanji: '変', readings: ['へん', 'か'], meanings: ['changer', 'bizarre', 'transformation'], level: 'N3' },
  { kanji: '形', readings: ['けい', 'ぎょう', 'かたち', 'かた'], meanings: ['forme', 'figure', 'apparence'], level: 'N3' },
  { kanji: '能', readings: ['のう'], meanings: ['capacité', 'talent', 'possible', 'Nô (théâtre)'], level: 'N3' },
  { kanji: '力', readings: ['りょく', 'りき', 'ちから'], meanings: ['force', 'puissance', 'capacité'], level: 'N3' },
  { kanji: '者', readings: ['しゃ', 'もの'], meanings: ['personne', 'expert', 'individu'], level: 'N3' },
  { kanji: '活', readings: ['かつ'], meanings: ['vivre', 'actif', 'activité'], level: 'N3' },
  { kanji: '動', readings: ['どう', 'うご'], meanings: ['bouger', 'mouvement', 'action'], level: 'N3' },
  { kanji: '問', readings: ['もん', 'と', 'とい'], meanings: ['question', 'problème', 'demander'], level: 'N3' },
  { kanji: '題', readings: ['だい'], meanings: ['titre', 'sujet', 'problème', 'question'], level: 'N3' },
];

export function getKanjiByLevel(level: JlptLevel | 'mixte'): KanjiEntry[] {
  if (level === 'mixte') return KANJI_DATA;
  return KANJI_DATA.filter((k) => k.level === level);
}

export function pickRandom<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function shuffled<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
